<?php

/**
 * Regression coverage for issue #94 (SEC-07): password reset tokens must be
 * generated by a CSPRNG, expire, and be invalidated after use or password
 * changes.
 */

$root = dirname(__DIR__);

foreach ([
  'MYSQL_HOST' => 'localhost',
  'MYSQL_USER' => 'root',
  'MYSQL_PASSWD' => '',
  'MYSQL_PORT' => '3306',
  'MYSQL_DATABASE' => 'krypto_test',
  'CRYPTED_KEY' => 'reset-password-token-security-test-key',
  'APP_URL' => $root,
  'APP_URL_FORCE' => false,
  'FILE_PATH' => '',
] as $constant => $value) {
  if(!defined($constant)) define($constant, $value);
}

require_once $root.'/vendor/autoload.php';
require_once $root.'/app/src/MySQL/MySQL.php';
require_once $root.'/app/src/App/App.php';
require_once $root.'/app/src/User/User.php';

function assert_reset_token_security($condition, $message) {
  if(!$condition) {
    throw new Exception($message);
  }
}

function reset_token_source_between($source, $startNeedle, $endNeedle) {
  $start = strpos($source, $startNeedle);
  assert_reset_token_security($start !== false, 'Cannot find source start: '.$startNeedle);
  $end = strpos($source, $endNeedle, $start);
  assert_reset_token_security($end !== false, 'Cannot find source end: '.$endNeedle);
  return substr($source, $start, $end - $start);
}

function reset_token_security_use_pdo(PDO $pdo) {
  $reflection = new ReflectionClass('MySQL');
  $property = $reflection->getProperty('bdd');
  $property->setAccessible(true);
  $property->setValue(null, $pdo);
}

function reset_token_security_store_user(PDO $pdo, $email, $token, $createdAt) {
  $statement = $pdo->prepare('INSERT INTO user_krypto (
      email_user,
      name_user,
      password_user,
      oauth_user,
      reset_token_user,
      reset_token_created_user
    ) VALUES (
      :email_user,
      :name_user,
      :password_user,
      :oauth_user,
      :reset_token_user,
      :reset_token_created_user
    )');
  $statement->execute([
    'email_user' => $email,
    'name_user' => 'Reset Token User',
    'password_user' => User::_hashPassword('old-password'),
    'oauth_user' => 'standard',
    'reset_token_user' => $token,
    'reset_token_created_user' => (string) $createdAt,
  ]);
}

function reset_token_security_link($email, $token) {
  return rawurlencode(App::_encryptSecret($email.'||--||'.$token));
}

class ResetPasswordTokenSecurityAppDouble {
  public static function _decryptSecret($value) {
    return App::_decryptSecret($value);
  }

  public function _getAppTitle() {
    return 'Krypto Test';
  }

  public function _getLogoBlackPath() {
    return '';
  }

  public function _getSupportEmail() {
    return 'support@example.test';
  }

  public function _sendMail($to, $subject, $body) {
    return true;
  }
}

$userSource = file_get_contents($root.'/app/src/User/User.php');
$installerSql = file_get_contents($root.'/install/assets/sql/krypto.sql');
$migrationPath = $root.'/install/assets/sql/security-sec07-reset-token-migration.sql';
$migrationSql = file_exists($migrationPath) ? file_get_contents($migrationPath) : '';

assert_reset_token_security($userSource !== false, 'Cannot read User.php.');
assert_reset_token_security($installerSql !== false, 'Cannot read installer SQL.');

$generateMethod = reset_token_source_between($userSource, 'private function _generateUserResetToken(', 'public function _resetPassword(');
$parseMethod = reset_token_source_between($userSource, 'public function _parseToken(', 'public function _validResetPassword(');
$validResetMethod = reset_token_source_between($userSource, 'public function _validResetPassword(', 'public function _getUserIP(');
$setPasswordMethod = reset_token_source_between($userSource, 'public function _setPassword(', 'public function _setEmail(');
$saveChangeMethod = reset_token_source_between($userSource, 'public function _saveChange(', 'public function _setFreetrial(');

assert_reset_token_security(strpos($userSource, 'bin2hex(random_bytes(32))') !== false, 'Reset tokens must be generated with bin2hex(random_bytes(32)).');
assert_reset_token_security(strpos($generateMethod, 'self::_generateResetPasswordTokenValue()') !== false, 'Reset token storage must use the CSPRNG token helper.');
assert_reset_token_security(strpos($generateMethod, 'str_shuffle') === false, 'Reset token generation must not use str_shuffle.');
assert_reset_token_security(strpos($generateMethod, 'reset_token_created_user=:reset_token_created_user') !== false, 'Reset token generation must persist the creation timestamp.');
assert_reset_token_security(strpos($parseMethod, '_isResetPasswordTokenExpired(') !== false, 'Reset token parsing must reject expired tokens.');
assert_reset_token_security(strpos($parseMethod, 'reset_token_created_user') !== false, 'Reset token parsing must read the token creation timestamp.');
assert_reset_token_security(strpos($parseMethod, '_invalidateResetTokensForEmail($tokenDecode[0], $tokenDecode[1])') !== false, 'Expired or consumed reset tokens must be invalidated.');
assert_reset_token_security(strpos($validResetMethod, 'reset_token_user = NULL') !== false, 'Successful password reset must clear reset_token_user.');
assert_reset_token_security(strpos($validResetMethod, 'reset_token_created_user = NULL') !== false, 'Successful password reset must clear reset_token_created_user.');
assert_reset_token_security(strpos($setPasswordMethod, '$this->resetTokensNeedInvalidation = true;') !== false, 'Manual password changes must mark reset tokens for invalidation.');
assert_reset_token_security(strpos($saveChangeMethod, '_invalidateResetTokensForEmail($this->_getEmail())') !== false, 'Saved password changes must invalidate reset tokens.');

assert_reset_token_security(strpos($installerSql, '`reset_token_created_user` varchar(15) DEFAULT NULL') !== false, 'Fresh installer schema must include reset_token_created_user.');
assert_reset_token_security(file_exists($migrationPath), 'SEC-07 reset token migration SQL must exist.');
assert_reset_token_security(strpos($migrationSql, 'ALTER TABLE `user_krypto`') !== false, 'SEC-07 migration must alter user_krypto.');
assert_reset_token_security(strpos($migrationSql, 'ADD COLUMN IF NOT EXISTS `reset_token_created_user` varchar(15) DEFAULT NULL') !== false, 'SEC-07 migration must add reset_token_created_user.');

$token = User::_generateResetPasswordTokenValue();
assert_reset_token_security(is_string($token) && preg_match('/\A[0-9a-f]{64}\z/', $token) === 1, 'Generated reset tokens must be 64 lowercase hex characters.');
assert_reset_token_security(count(array_unique(str_split($token))) < strlen($token), 'Generated reset tokens must allow repeated characters.');

$now = 2000000000;
assert_reset_token_security(User::_isValidResetPasswordToken($token), 'Fresh generated reset tokens must pass format validation.');
assert_reset_token_security(!User::_isValidResetPasswordToken('short-token'), 'Malformed reset tokens must fail validation.');
assert_reset_token_security(!User::_isResetPasswordTokenExpired((string) ($now - 3599), $now), 'Reset tokens younger than the TTL must remain valid.');
assert_reset_token_security(User::_isResetPasswordTokenExpired((string) ($now - 3601), $now), 'Reset tokens older than the TTL must expire.');
assert_reset_token_security(User::_isResetPasswordTokenExpired('', $now), 'Reset tokens without a creation timestamp must expire.');

$pdo = new PDO('sqlite::memory:');
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$pdo->exec('CREATE TABLE user_krypto (
  email_user text NOT NULL,
  name_user text NOT NULL,
  password_user text NOT NULL,
  oauth_user text NOT NULL,
  reset_token_user text,
  reset_token_created_user text
)');
reset_token_security_use_pdo($pdo);

$app = new ResetPasswordTokenSecurityAppDouble();
$user = new User();

$oneTimeEmail = 'one-time@example.test';
$oneTimeToken = User::_generateResetPasswordTokenValue();
reset_token_security_store_user($pdo, $oneTimeEmail, $oneTimeToken, time());
$oneTimeLink = reset_token_security_link($oneTimeEmail, $oneTimeToken);
assert_reset_token_security($user->_parseToken($app, $oneTimeLink) === [$oneTimeEmail, $oneTimeToken], 'Fresh reset token must parse before use.');
assert_reset_token_security($user->_parseToken($app, $oneTimeLink, true) === [$oneTimeEmail, $oneTimeToken], 'Fresh reset token must parse when consumed.');
assert_reset_token_security($user->_parseToken($app, $oneTimeLink) === false, 'Consumed reset token must not parse again.');

$expiredEmail = 'expired@example.test';
$expiredToken = User::_generateResetPasswordTokenValue();
reset_token_security_store_user($pdo, $expiredEmail, $expiredToken, time() - User::RESET_PASSWORD_TOKEN_TTL_SECONDS - 1);
$expiredLink = reset_token_security_link($expiredEmail, $expiredToken);
assert_reset_token_security($user->_parseToken($app, $expiredLink) === false, 'Expired reset token must be rejected.');
$expiredRow = $pdo->query("SELECT reset_token_user, reset_token_created_user FROM user_krypto WHERE email_user = 'expired@example.test'")->fetch(PDO::FETCH_ASSOC);
assert_reset_token_security($expiredRow['reset_token_user'] === null && $expiredRow['reset_token_created_user'] === null, 'Expired reset token must be invalidated in storage.');

$resetEmail = 'reset@example.test';
$resetToken = User::_generateResetPasswordTokenValue();
reset_token_security_store_user($pdo, $resetEmail, $resetToken, time());
$resetLink = reset_token_security_link($resetEmail, $resetToken);
assert_reset_token_security($user->_validResetPassword($resetLink, $app, 'new-password'), 'Valid reset token must update the password.');
$resetRow = $pdo->query("SELECT password_user, reset_token_user, reset_token_created_user FROM user_krypto WHERE email_user = 'reset@example.test'")->fetch(PDO::FETCH_ASSOC);
assert_reset_token_security(User::_passwordMatches('new-password', $resetRow['password_user']), 'Password reset must persist the new password hash.');
assert_reset_token_security($resetRow['reset_token_user'] === null && $resetRow['reset_token_created_user'] === null, 'Successful password reset must invalidate reset token storage.');
assert_reset_token_security($user->_parseToken($app, $resetLink) === false, 'Successful password reset must make the token one-time.');

echo "Reset password token security checks passed.\n";

?>
