<?php

/**
 * CoinbaseCommerce class
 *
 * @package Krypto
 * @author Ovrley <hello@ovrley.com>
 */
class CoinbaseCommerceDepositProcessor {

  private $repository;

  public function __construct($repository){
    $this->repository = $repository;
  }

  public function _processWebhook($payload, $rawBody, $signature, $webhookSecret){
    self::_validateSignature($rawBody, $signature, $webhookSecret);

    $eventType = self::_eventType($payload);
    if($eventType == 'charge:confirmed'){
      return $this->_confirmTransaction($payload);
    }

    return [
      'status' => 'ignored',
      'event_type' => $eventType
    ];
  }

  public function _confirmTransaction($payload){
    $payment = self::_validatedConfirmedCharge($payload);

    $processed = $this->repository->_findProcessedCoinbaseCommerceDeposit($payment['charge_id'], $payment['user_id']);
    if(!is_null($processed)){
      return [
        'status' => 'duplicate',
        'charge_id' => $payment['charge_id']
      ];
    }

    $deposit = $this->repository->_findPendingCoinbaseCommerceDeposit($payment['charge_id'], $payment['user_id'], $payment['deposit_reference']);
    if(!is_array($deposit)) throw new Exception('Coinbase Commerce pending deposit not found.', 1);

    self::_assertDepositMatchesPayment($deposit, $payment);

    $confirmed = $this->repository->_confirmCoinbaseCommerceDeposit($deposit, '1');
    if(!$confirmed) throw new Exception('Coinbase Commerce deposit confirmation failed.', 1);

    return [
      'status' => 'confirmed',
      'charge_id' => $payment['charge_id']
    ];
  }

  public static function _expectedSignature($rawBody, $webhookSecret){
    return hash_hmac("sha256", (string) $rawBody, (string) $webhookSecret);
  }

  public static function _validateSignature($rawBody, $signature, $webhookSecret){
    $secret = trim((string) $webhookSecret);
    if($secret === '') throw new Exception('Coinbase Commerce webhook secret is not configured.', 1);
    if(!is_scalar($signature) || trim((string) $signature) === '') throw new Exception("Webhook signature not included in the headers of the request.", 1);

    $hash = self::_expectedSignature((string) $rawBody, $secret);
    if(!hash_equals($hash, trim((string) $signature))) {
      throw new Exception("The webhook signature of the request does not match the one generated by the server.", 1);
    }

    return true;
  }

  public static function _eventType($payload){
    if(!is_array($payload) || !array_key_exists('event', $payload) || !is_array($payload['event'])) {
      throw new Exception("Request needs to contain 'event' value.", 1);
    }

    return self::_requiredScalar($payload['event'], 'type', 'Coinbase Commerce event type');
  }

  private static function _validatedConfirmedCharge($payload){
    $eventType = self::_eventType($payload);
    if($eventType !== 'charge:confirmed') throw new Exception('Coinbase Commerce event is not a confirmed charge.', 1);

    $event = $payload['event'];
    if(!array_key_exists('data', $event) || !is_array($event['data'])) throw new Exception("Error Coinbase Commerce : Invalid payment", 1);
    if(!array_key_exists('metadata', $event['data']) || !is_array($event['data']['metadata'])) throw new Exception("Error Coinbase Commerce : Invalid payment", 1);

    $payment = [
      'event_id' => self::_requiredScalar($event, 'id', 'Coinbase Commerce event id'),
      'charge_id' => self::_requiredScalar($event['data'], 'id', 'Coinbase Commerce charge id'),
      'deposit_reference' => self::_requiredScalar($event['data']['metadata'], 'deposit_reference', 'Coinbase Commerce deposit reference'),
      'user_id' => self::_requiredScalar($event['data']['metadata'], 'id_user', 'Coinbase Commerce user id')
    ];

    self::_assertProviderIdentifier($payment['event_id'], 'Coinbase Commerce event id');
    self::_assertProviderIdentifier($payment['charge_id'], 'Coinbase Commerce charge id');
    self::_assertProviderIdentifier($payment['deposit_reference'], 'Coinbase Commerce deposit reference');

    if(!preg_match('/^[0-9]{1,20}$/', $payment['user_id'])){
      throw new Exception('Coinbase Commerce user id is invalid.', 1);
    }

    return $payment;
  }

  private static function _requiredScalar($data, $field, $label){
    if(!array_key_exists($field, $data) || !is_scalar($data[$field])){
      throw new Exception($label.' is missing.', 1);
    }

    $value = trim((string) $data[$field]);
    if($value === '') throw new Exception($label.' is empty.', 1);
    return $value;
  }

  private static function _assertProviderIdentifier($value, $label){
    if(strlen((string) $value) > 191 || preg_match('/[\x00-\x1F\x7F]/', (string) $value)){
      throw new Exception($label.' is invalid.', 1);
    }
  }

  private static function _assertDepositMatchesPayment($deposit, $payment){
    if((string) $deposit['id_user'] !== (string) $payment['user_id']){
      throw new Exception('Coinbase Commerce deposit user mismatch.', 1);
    }

    if(strtolower((string) $deposit['payment_type_deposit_history']) !== 'coinbasecommerce'){
      throw new Exception('Coinbase Commerce deposit type mismatch.', 1);
    }

    if((string) $deposit['payment_status_deposit_history'] !== '0'){
      throw new Exception('Coinbase Commerce deposit is not pending.', 1);
    }

    if((string) $deposit['payment_data_deposit_history'] !== (string) $payment['charge_id']){
      throw new Exception('Coinbase Commerce charge id mismatch.', 1);
    }

    if((string) $deposit['ref_deposit_history'] !== (string) $payment['deposit_reference']){
      throw new Exception('Coinbase Commerce deposit reference mismatch.', 1);
    }
  }
}

class CoinbaseCommerce extends MySQL
{
    /**
     * App object
     * @var App
     */
    private $App = null;

    private $CoinbaseCommerce = null;

    /**
     * RaveFlutterwave constructor
     * @param App $App          App object
     */
    public function __construct($App = null)
    {
        if (is_null($App)) {
            throw new Exception("Error CoinbaseCommerce : App need to be given", 1);
        }
        $this->App = $App;

    }
    /**
     * Get app object
     * @return App App object
     */
    private function _getApp()
    {
        if (is_null($this->App)) {
            throw new Exception("Error CoinbaseCommerce : App not defined", 1);
        }
        return $this->App;
    }

    public function _init(){
      if(!$this->_getApp()->_coinbasecommerceEnabled()) throw new Exception("Error Coinbase Commerce is not enabled", 1);
      $this->CoinbaseCommerce = new \WPDMPP\Coinbase\Commerce\Client();
      $this->CoinbaseCommerce->setApiKey($this->_getApp()->_getCoinbaseCommerceAPIKey());
    }

    public function _getCoinbaseCommerce(){
      if(is_null($this->CoinbaseCommerce)) $this->_init();
      return $this->CoinbaseCommerce;
    }

    public function _getCurrencyAvailable(){
      return ['USD', 'EUR', 'JPY', 'GBP', 'AUD', 'CAD', 'CHF', 'CNY', 'SEK',
              'NZD', 'MXN', 'SGD', 'HKD', 'NOK', 'KRW', 'TRY', 'RUB', 'INR',
              'BRL', 'ZAR', 'AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS',
              'AWG', 'AZN', 'BAM', 'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD',
              'BND', 'BOB', 'BSD', 'BTN', 'BWP', 'BYN', 'BZD', 'CDF', 'CLF',
              'CLP', 'COP', 'CRC', 'CUC', 'CUP', 'CVE', 'CZK', 'DJF', 'DKK',
              'DOP', 'DZD', 'EGP', 'ERN', 'ETB', 'FJD', 'FKP', 'GEL', 'GGP',
              'GHS', 'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HNL', 'HRK', 'HTG',
              'HUF', 'IDR', 'ILS', 'IMP', 'IQD', 'IRR', 'ISK', 'JEP', 'JMD',
              'JOD', 'KES', 'KGS', 'KHR', 'KMF', 'KPW', 'KWD', 'KYD', 'KZT',
              'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LYD', 'MAD', 'MDL', 'MGA',
              'MKD', 'MMK', 'MNT', 'MOP', 'MRO', 'MUR', 'MVR', 'MWK', 'MYR',
              'MZN', 'NAD', 'NGN', 'NIO', 'NPR', 'OMR', 'PAB', 'PEN', 'PGK',
              'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RWF', 'SAR',
              'SBD', 'SCR', 'SDG', 'SHP', 'SLL', 'SOS', 'SRD', 'SSP', 'STD',
              'SVC', 'SYP', 'SZL', 'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TTD',
              'TWD', 'TZS', 'UAH', 'UGX', 'UYU', 'UZS', 'VEF', 'VND', 'VUV',
              'WST', 'XAF', 'XAG', 'XAU', 'XCD', 'XDR', 'XOF', 'XPD', 'XPF',
              'XPT', 'YER', 'ZMW', 'ZWL'];
    }

    public function _createNewPayment($User, $Amount, $BalanceUser, $Currency){

      $Currency = (in_array($Currency, $this->_getCurrencyAvailable()) ? $Currency : $this->_getCurrencyAvailable()[0]);

      $charge = new \WPDMPP\Coinbase\Commerce\Model\Charge();

      $money = new \WPDMPP\Coinbase\Commerce\Model\Money();
      $money->SetAmount($Amount);
      $money->SetCurrency($Currency);

      $DepositReference = $BalanceUser->_addDeposit($Amount, 'coinbasecommerce', 'Payment Coinbase Commerce '.$Amount.' '.$Currency, $Currency, "-not-filled-yet-".App::encrypt_decrypt('encrypt', time().rand(0, 9999999).time()), 0);

      $charge->setName($this->_getApp()->_getCoinbaseCommercePaymentTitle());
      $charge->setDescription($DepositReference.' - '.$this->_getApp()->_formatNumber($Amount, 2).' '.$Currency.' - Deposit');
      $charge->setPricingType('fixed_price');
      $charge->setLocalPrice($money);
      $charge->addMetadata('id_user', $User->_getUserID());


      $charge->addMetadata('deposit_reference', $DepositReference);

      $charge->setRedirectUrl(APP_URL.'/app/modules/kr-payment/src/actions/deposit/processCoinbaseCommerce.php');

      $response = $this->_getCoinbaseCommerce()->createCharge($charge);

      $responseDecoded = json_decode($response);
      $BalanceUser->_updateDepositPaymentData($DepositReference, $responseDecoded->data->id);

      return $responseDecoded->data->hosted_url;

    }

    public function _parseWebhook($payload, $rawBody = null, $signature = null){
      if(is_null($rawBody)) $rawBody = file_get_contents('php://input');
      if(is_null($signature) && array_key_exists('HTTP_X_CC_WEBHOOK_SIGNATURE', $_SERVER)) $signature = $_SERVER['HTTP_X_CC_WEBHOOK_SIGNATURE'];

      $processor = new CoinbaseCommerceDepositProcessor($this);
      return $processor->_processWebhook($payload, $rawBody, $signature, $this->_getApp()->_getCoinbaseCommerceWebhookSecret());
    }

    public function _confirmTransaction($payload){
      $processor = new CoinbaseCommerceDepositProcessor($this);
      return $processor->_confirmTransaction($payload);
    }

    public function _validateRequest($payload, $rawBody = null, $signature = null){
      if(is_null($rawBody)) $rawBody = file_get_contents('php://input');
      if(is_null($signature) && array_key_exists('HTTP_X_CC_WEBHOOK_SIGNATURE', $_SERVER)) $signature = $_SERVER['HTTP_X_CC_WEBHOOK_SIGNATURE'];

      CoinbaseCommerceDepositProcessor::_validateSignature($rawBody, $signature, $this->_getApp()->_getCoinbaseCommerceWebhookSecret());
      CoinbaseCommerceDepositProcessor::_eventType($payload);
      return true;
    }

    public function _findProcessedCoinbaseCommerceDeposit($chargeId, $userId){
      $r = parent::querySqlRequest("SELECT * FROM deposit_history_krypto
                                    WHERE id_user=:id_user
                                      AND payment_type_deposit_history=:payment_type_deposit_history
                                      AND payment_status_deposit_history<>:pending_status
                                      AND payment_data_deposit_history=:payment_data_deposit_history
                                    ORDER BY id_deposit_history DESC LIMIT 1",
                                  [
                                    'id_user' => $userId,
                                    'payment_type_deposit_history' => 'coinbasecommerce',
                                    'pending_status' => '0',
                                    'payment_data_deposit_history' => $chargeId
                                  ]);

      return (count($r) > 0 ? $r[0] : null);
    }

    public function _findPendingCoinbaseCommerceDeposit($chargeId, $userId, $depositReference){
      $r = parent::querySqlRequest("SELECT * FROM deposit_history_krypto
                                    WHERE id_user=:id_user
                                      AND ref_deposit_history=:ref_deposit_history
                                      AND payment_type_deposit_history=:payment_type_deposit_history
                                      AND payment_status_deposit_history=:payment_status_deposit_history
                                      AND payment_data_deposit_history=:payment_data_deposit_history
                                    ORDER BY id_deposit_history DESC LIMIT 1",
                                  [
                                    'id_user' => $userId,
                                    'ref_deposit_history' => $depositReference,
                                    'payment_type_deposit_history' => 'coinbasecommerce',
                                    'payment_status_deposit_history' => '0',
                                    'payment_data_deposit_history' => $chargeId
                                  ]);

      return (count($r) > 0 ? $r[0] : null);
    }

    public function _confirmCoinbaseCommerceDeposit($deposit, $status){
      if(!is_array($deposit) || !array_key_exists('id_deposit_history', $deposit)) return false;

      $req = self::getSqlConnexion()->prepare("UPDATE deposit_history_krypto
                                                SET payment_status_deposit_history=:payment_status_deposit_history
                                                WHERE id_deposit_history=:id_deposit_history
                                                  AND id_user=:id_user
                                                  AND ref_deposit_history=:ref_deposit_history
                                                  AND payment_type_deposit_history=:payment_type_deposit_history
                                                  AND payment_status_deposit_history=:pending_status
                                                  AND payment_data_deposit_history=:charge_id");
      $ok = $req->execute([
        'payment_status_deposit_history' => (string) $status,
        'id_deposit_history' => $deposit['id_deposit_history'],
        'id_user' => $deposit['id_user'],
        'ref_deposit_history' => $deposit['ref_deposit_history'],
        'payment_type_deposit_history' => 'coinbasecommerce',
        'pending_status' => '0',
        'charge_id' => $deposit['payment_data_deposit_history']
      ]);
      $updatedRows = $req->rowCount();
      $req->closeCursor();

      return $ok && $updatedRows === 1;
    }


}
