CREATE TABLE IF NOT EXISTS `changenow_transactions_krypto` (
  `id_changenow_transaction` int(11) NOT NULL AUTO_INCREMENT,
  `provider_id_changenow_transaction` varchar(120) NOT NULL,
  `lookup_token_hash_changenow_transaction` char(64) NOT NULL,
  `session_key_changenow_transaction` char(64) NOT NULL,
  `id_user` int(11) DEFAULT NULL,
  `flow_changenow_transaction` varchar(20) NOT NULL DEFAULT 'standard',
  `from_currency_changenow_transaction` varchar(32) NOT NULL,
  `from_network_changenow_transaction` varchar(32) NOT NULL,
  `to_currency_changenow_transaction` varchar(32) NOT NULL,
  `to_network_changenow_transaction` varchar(32) NOT NULL,
  `from_amount_changenow_transaction` varchar(40) NOT NULL,
  `to_amount_changenow_transaction` varchar(40) DEFAULT NULL,
  `payin_address_changenow_transaction` text,
  `payin_extra_id_changenow_transaction` varchar(255) DEFAULT NULL,
  `payout_address_changenow_transaction` text,
  `payout_extra_id_changenow_transaction` varchar(255) DEFAULT NULL,
  `refund_address_changenow_transaction` text,
  `refund_extra_id_changenow_transaction` varchar(255) DEFAULT NULL,
  `status_changenow_transaction` varchar(40) NOT NULL DEFAULT 'waiting',
  `raw_create_changenow_transaction` longtext,
  `raw_status_changenow_transaction` longtext,
  `created_at_changenow_transaction` varchar(15) NOT NULL,
  `updated_at_changenow_transaction` varchar(15) NOT NULL,
  `expires_at_changenow_transaction` varchar(15) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_changenow_transaction`),
  UNIQUE KEY `provider_id_changenow_transaction` (`provider_id_changenow_transaction`),
  UNIQUE KEY `lookup_token_hash_changenow_transaction` (`lookup_token_hash_changenow_transaction`),
  KEY `session_key_changenow_transaction` (`session_key_changenow_transaction`),
  KEY `user_changenow_transaction` (`id_user`),
  KEY `status_changenow_transaction` (`status_changenow_transaction`),
  KEY `pair_changenow_transaction` (`from_currency_changenow_transaction`, `from_network_changenow_transaction`, `to_currency_changenow_transaction`, `to_network_changenow_transaction`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
